### ISSUE TITLE
Automatic packagist update

### ISSUE THREAD

**Issue by remilemonnier** [M6Web/Redis#22]
Could you add a hook on your repo to update automatically new tags on packagist?

The last tag available for this bundle on packagist is 2.5.0

How to:
https://www.idci-consulting.fr/fr/article/bundle-composer-broadcast

Thanks!

**Comment by omansour** [comment]
sure ? https://packagist.org/packages/m6web/redis-component

**Comment by remilemonnier** [comment]
Ok, my fault, I confuse the component and the bundle.
